use parseapi::*;

#[test]
fn adp_models_decode_absent_locked_and_populated_depth() {
 let plain: Country = serde_json::from_str(r#"{"country":"US","name":"United States","continent":"NA"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Country = serde_json::from_str(r#"{"country":"US","name":"United States","continent":"NA","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Country = serde_json::from_str(r#"{"country":"US","name":"United States","continent":"NA","deep":{"iso3":"USA","population":0,"tax_rate":0,"plugs":[]}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: State = serde_json::from_str(r#"{"state":"NC","name":"North Carolina","country":"US"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: State = serde_json::from_str(r#"{"state":"NC","name":"North Carolina","country":"US","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: State = serde_json::from_str(r#"{"state":"NC","name":"North Carolina","country":"US","deep":{"population":0,"area":0.25,"tax_rate":0}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: District = serde_json::from_str(r#"{"district":"37081","name":"Guilford","country":"US"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: District = serde_json::from_str(r#"{"district":"37081","name":"Guilford","country":"US","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: District = serde_json::from_str(r#"{"district":"37081","name":"Guilford","country":"US","deep":{"population":0,"water_area":0.25}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: City = serde_json::from_str(r#"{"name":"Charlotte","country":"US","id":"city_123"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: City = serde_json::from_str(r#"{"name":"Charlotte","country":"US","id":"city_123","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: City = serde_json::from_str(r#"{"name":"Charlotte","country":"US","id":"city_123","deep":{"population":0,"area":0.25}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Postal = serde_json::from_str(r#"{"postal":"28202","country":"US"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Postal = serde_json::from_str(r#"{"postal":"28202","country":"US","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Postal = serde_json::from_str(r#"{"postal":"28202","country":"US","deep":{"metros":[],"water_area":0.25,"tax_rate":0}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Iban = serde_json::from_str(r#"{"iban":"DE89370400440532013000","valid":true}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Iban = serde_json::from_str(r#"{"iban":"DE89370400440532013000","valid":true,"deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Iban = serde_json::from_str(r#"{"iban":"DE89370400440532013000","valid":true,"deep":{"checksum":"89","branch":null,"account":"0532013000"}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Npi = serde_json::from_str(r#"{"npi":"1881018208","valid":true,"excluded":true,"credential":"MD","state_name":"Minnesota"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Npi = serde_json::from_str(r#"{"npi":"1881018208","valid":true,"excluded":true,"credential":"MD","state_name":"Minnesota","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Npi = serde_json::from_str(r#"{"npi":"1881018208","valid":true,"excluded":true,"credential":"MD","state_name":"Minnesota","deep":{"deactivated_at":"2026-09-01","enrollments":[]}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Vin = serde_json::from_str(r#"{"vin":"1HGCM82633A004352","valid":true,"make":"Honda"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Vin = serde_json::from_str(r#"{"vin":"1HGCM82633A004352","valid":true,"make":"Honda","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Vin = serde_json::from_str(r#"{"vin":"1HGCM82633A004352","valid":true,"make":"Honda","deep":{"horsepower":240.5,"recalls":[]}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Phone = serde_json::from_str(r#"{"phone":"+14155552671","valid":true}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Phone = serde_json::from_str(r#"{"phone":"+14155552671","valid":true,"deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Phone = serde_json::from_str(r#"{"phone":"+14155552671","valid":true,"deep":{"state":"CA","timezone":"America/Los_Angeles"}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Carrier = serde_json::from_str(r#"{"phone":"+14155552671","valid":true,"carrier":"Example"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Carrier = serde_json::from_str(r#"{"phone":"+14155552671","valid":true,"carrier":"Example","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Carrier = serde_json::from_str(r#"{"phone":"+14155552671","valid":true,"carrier":"Example","deep":{"city":"San Francisco","state":"CA"}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Hlr = serde_json::from_str(r#"{"phone":"+14155552671","valid":true,"live":true,"connected":false}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Hlr = serde_json::from_str(r#"{"phone":"+14155552671","valid":true,"live":true,"connected":false,"deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Hlr = serde_json::from_str(r#"{"phone":"+14155552671","valid":true,"live":true,"connected":false,"deep":{"roaming":false,"mcc":"310","mnc":"01"}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Tariff = serde_json::from_str(r#"{"hts":"8471.30.01.00","description":"Portable computers","revision":"2026"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Tariff = serde_json::from_str(r#"{"hts":"8471.30.01.00","description":"Portable computers","revision":"2026","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Tariff = serde_json::from_str(r#"{"hts":"8471.30.01.00","description":"Portable computers","revision":"2026","deep":{"units":[],"special":"Free","origin":null,"effective_rate":null,"measures":null}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Naics = serde_json::from_str(r#"{"naics":"541511","name":"Programming","level":6,"parent":"54151","year":2022,"country":"US"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Naics = serde_json::from_str(r#"{"naics":"541511","name":"Programming","level":6,"parent":"54151","year":2022,"country":"US","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Naics = serde_json::from_str(r#"{"naics":"541511","name":"Programming","level":6,"parent":"54151","year":2022,"country":"US","deep":{"description":"Definition","children":[],"exclusions":[]}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Company = serde_json::from_str(r#"{"company":"01234567","valid":true,"name":"Example"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Company = serde_json::from_str(r#"{"company":"01234567","valid":true,"name":"Example","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Company = serde_json::from_str(r#"{"company":"01234567","valid":true,"name":"Example","deep":{"activity":"6201","gst":false,"vat":null}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Currency = serde_json::from_str(r#"{"currency":"USD","name":"US Dollar"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Currency = serde_json::from_str(r#"{"currency":"USD","name":"US Dollar","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Currency = serde_json::from_str(r#"{"currency":"USD","name":"US Dollar","deep":{"numeric":840,"countries":[]}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Language = serde_json::from_str(r#"{"language":"en","name":"English","direction":"ltr"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Language = serde_json::from_str(r#"{"language":"en","name":"English","direction":"ltr","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Language = serde_json::from_str(r#"{"language":"en","name":"English","direction":"ltr","deep":{"iso3":"eng","countries":[]}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Name = serde_json::from_str(r#"{"name":"Andrea","valid":true,"first":"Andrea"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Name = serde_json::from_str(r#"{"name":"Andrea","valid":true,"first":"Andrea","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Name = serde_json::from_str(r#"{"name":"Andrea","valid":true,"first":"Andrea","deep":{"known":false,"gender":null,"countries":[]}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Timezone = serde_json::from_str(r#"{"timezone":"UTC","unix":0,"at":"1970-01-01T00:00:00+00:00","offset":"+00:00","dst":false}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Timezone = serde_json::from_str(r#"{"timezone":"UTC","unix":0,"at":"1970-01-01T00:00:00+00:00","offset":"+00:00","dst":false,"deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Timezone = serde_json::from_str(r#"{"timezone":"UTC","unix":0,"at":"1970-01-01T00:00:00+00:00","offset":"+00:00","dst":false,"deep":{"name":"UTC","offset_seconds":0,"offset_minutes":0,"next_dst":null}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: DateInfo = serde_json::from_str(r#"{"date":"1970-01-01","valid":true,"unix":0}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: DateInfo = serde_json::from_str(r#"{"date":"1970-01-01","valid":true,"unix":0,"deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: DateInfo = serde_json::from_str(r#"{"date":"1970-01-01","valid":true,"unix":0,"deep":{"year":1970,"weekday":4,"leap":false}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Emoji = serde_json::from_str(r#"{"emoji":"😀","name":"grinning face","shortcodes":[]}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Emoji = serde_json::from_str(r#"{"emoji":"😀","name":"grinning face","shortcodes":[],"deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Emoji = serde_json::from_str(r#"{"emoji":"😀","name":"grinning face","shortcodes":[],"deep":{"hex":"1F600","skins":[]}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Point = serde_json::from_str(r#"{"latitude":0,"longitude":0,"timezone":"Etc/GMT"}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Point = serde_json::from_str(r#"{"latitude":0,"longitude":0,"timezone":"Etc/GMT","deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Point = serde_json::from_str(r#"{"latitude":0,"longitude":0,"timezone":"Etc/GMT","deep":{"elevation":0.25,"city":{"name":"Place","id":"city_123","type":"city","distance":0.5}}}"#).unwrap();
 assert!(rich.deep.is_some());
 let plain: Weather = serde_json::from_str(r#"{"latitude":0,"longitude":0,"current":{"temperature":0,"observed_at":"2026-09-08T12:00:00Z"}}"#).unwrap();
 assert!(plain.deep.is_none());
 let rich: Weather = serde_json::from_str(r#"{"latitude":0,"longitude":0,"current":{"temperature":0,"observed_at":"2026-09-08T12:00:00Z"},"deep":{}}"#).unwrap();
 assert!(rich.deep.is_some());
 let rich: Weather = serde_json::from_str(r#"{"latitude":0,"longitude":0,"current":{"temperature":0,"observed_at":"2026-09-08T12:00:00Z"},"deep":{"current":{"pressure":1012.5,"wind_gust":0},"forecast":[]}}"#).unwrap();
 assert!(rich.deep.is_some());
}

#[test]
fn nested_district_profiles_and_clock_targets_preserve_zero() {
 let listing: StateDistricts = serde_json::from_str(r#"{"state":"NC","country":"US","districts":[{"district":"37081","name":"Guilford","deep":{"population":0}}]}"#).unwrap();
 assert_eq!(listing.districts[0].deep.as_ref().unwrap().population,Some(0));
 let clock: Time = serde_json::from_str(r#"{"timezone":"UTC","unix":0,"deep":{"offset_seconds":0,"next_dst":null},"to":{"timezone":"UTC","unix":0,"deep":{"offset_seconds":0}}}"#).unwrap();
 assert_eq!(clock.to.unwrap().deep.unwrap().offset_seconds,Some(0));
}
